version: '2.3'
services:
  onlyoffice:
    # Tweak these according to your needs.
    mem_limit: 4g
    cpus: 4.00
    image: 'onlyoffice/documentserver:latest'
    restart: always
    stdin_open: true
    tty: true
    # Volumes are optional.
    # uids and gids are for people who are using docker with user namespaces enabled.
    #volumes:
      # If you want to manually change the settings (i.e. secret key). The file is owned by root by default, but removing o+r causes the container to crash, so you probably want to try the onlyoffice user (uid 110, gid 114).
      # NOTE: Do not supply your own default.json. It changes too often and you'll be stuck manually updating it pretty much every time you update.
      #- config/local.json:/etc/onlyoffice/documentserver/local.json
      # Database. Must be owned by the postgres user (uid 107, gid 111).
      #- db:/var/lib/postgresql
      # Logs. Must be owned by the onlyoffice user.
      #- /var/log/onlyoffice:/var/log/onlyoffice
      # Data. Useful if you want to use https for the connection with forward facing proxy (or public). Must be owned by root.
      #- data:/var/www/onlyoffice/Data
    ports:
      - '127.0.0.1:8016:80'
    # If using software like sslh, it's you'll probably need to specify a hostname for your nextcloud instance manually
    # since it fails to connect otherwise. Remember to make your nextcloud's nginx server listen to this IP address.
    #extra_hosts:
        #- 'hostname:container ip'
